# Generated by Django 6.0.7 on 2026-07-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('scientific_name', models.CharField(max_length=150)),
                ('species', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('habitat', models.TextField()),
                ('diet', models.CharField(max_length=100)),
                ('lifespan', models.PositiveSmallIntegerField(help_text='Average lifespan in years')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Average weight in kg', max_digits=8)),
                ('height', models.DecimalField(decimal_places=2, help_text='Average height in cm', max_digits=6)),
                ('conservation_status', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='animals/images/')),
                ('is_endangered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'animals_animal',
                'ordering': ['name'],
            },
        ),
    ]
